### ISSUE TITLE
address feedback in pull request #3

### ISSUE THREAD

**Issue by afeld** [18F/newrelic-terraform#13]
## Background information

Just came across https://github.com/18F/newrelic-terraform/pull/3 again; there were a number of comments in there that weren't addressed.

## Acceptance criteria

- Explanation given and/or feedback addressed on `master`

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by JJediny** [comment]
Addressed the feedback, as I changed the workflow for updating the specific comments have changed. But intent of this issue is understood and I'll make sure to avoid large PRs and documenting responses back to reviews moving forward.
