### ISSUE TITLE
set up remote state

### ISSUE THREAD

**Issue by afeld** [18F/newrelic-terraform#19]
## Background Information

Blocker for https://github.com/18F/newrelic-terraform/issues/16.

## Implementation Steps
- [x] Add S3 terraform resources

## Acceptance Criteria

- [x] Both @JJediny and @afeld able to run an `plan` locally and show no changes

**Comment by adborden** [comment]
Currently, it's a manual step to download the website inventory. We're going to leave that as a manual step and add a script that will filter/process the inventory to only the rows of sites needed for terraform.

**Comment by afeld** [comment]
If we want to take that manual step out of the critical path, totally fine to check the filtered list into the repository.

**Comment by adborden** [comment]
Completed in https://github.com/18F/newrelic-terraform/pull/22
