### ISSUE TITLE
set up single sign-on (SSO) for New Relic users - due 2/21

### ISSUE THREAD

**Issue by afeld** [18F/newrelic-terraform#9]
Setup GSA Secureauth (and login.gov?)  for New Relic SSO for TTS developers to meet FEDRAMP Moderate Customer Responsibilities. 

## Implementation
- [x] Request for a new SAML connection made through servicenow
   - [x] Setup a new auth endpoint from login.gov dashboard
- [x] Secureauth dev/test MVP validated w/ existing users
   - [ ] Login.gov dev/test MVP validated w/ existing users
- [x] [Write communication to send to users](https://docs.google.com/document/d/1tLspN3wgsAXzHjogjJkOVoOxWkAQQnDX5rhCf5XtRGk/edit)
- [x] Send notice to users
- [x] Flip the switch
- [x] Update POA&M

## Acceptance
- [x] Users sign into New Relic using single sign-on

**Comment by afeld** [comment]
@its-a-lisa-at-work This was a POAM item, right? Is there a due date for that?

**Comment by afeld** [comment]
From Tamara:

> The New Relic cert letter is going for signatures today, so this starts the 90 day clock to have MFA/SSO implemented for the GSA instance of New Relic.
>
> These controls in the SSP marked as "planned" (all requiring SSO) are going on the EAS POA&M with a 90 day deadline as of today.

**Comment by afeld** [comment]
I believe we are all set here.

**Comment by afeld** [comment]
Documenting here for posterity: @JJediny spent a _lot_ of time going back and forth with the New Relic and GSA SecureAuth teams trying to make SecureAuth work off the VPN. Due to a lack of configuration options on the New Relic side and/or a bug somewhere, it wasn't easy/possible. We will document the requirement to be on the network in https://github.com/18F/handbook/issues/2553.

**Comment by adborden** [comment]
This sucks for contractors who have to access the GSA network over Horizon/Citrix. It prevents them from accessing NR directly from their laptop.

**Comment by afeld** [comment]
Contractors who are accessing New Relic should probably be using GSA-issued machines. Whole separate problem. https://github.com/18F/tts-tech-portfolio/issues/1340
